In [21]:
from graphdatascience.session import DbmsConnectionInfo, AlgorithmCategory, CloudLocation, GdsSessions, AuraAPICredentials
from datetime import timedelta
import pandas as pd
import os
from dotenv import load_dotenv

In [22]:
load_dotenv()

# This credential is the Organization ID
TENANT_ID = os.environ["TENANT_ID"]

# These credentials were generated after the creation of the API Endpoint
CLIENT_SECRET = os.environ["CLIENT_SECRET"]
CLIENT_ID = os.environ["CLIENT_ID"]

## Set Up Sessions
Set up sessions with credentials and then spin up a *session*

In [23]:
from graphdatascience.session import GdsSessions, AuraAPICredentials, AlgorithmCategory, CloudLocation
from datetime import timedelta

sessions = GdsSessions(api_credentials=AuraAPICredentials(CLIENT_ID, CLIENT_SECRET, TENANT_ID))

name = "my-new-session-sm"
memory = sessions.estimate(
    node_count=20,
    relationship_count=50,
    algorithm_categories=[AlgorithmCategory.CENTRALITY, AlgorithmCategory.NODE_EMBEDDING],
)
cloud_location = CloudLocation(provider="gcp", region="europe-west1")

gds = sessions.get_or_create(
    session_name=name,
    memory=memory,
    ttl=timedelta(hours=5),
    cloud_location=cloud_location,
)

## Load in Data
Load in data from my github that covers how the NYC subway connects together.

In [9]:
import pandas as pd
import snowflake.connector
load_dotenv()

SNOWFLAKE_USER = os.environ["SNOWFLAKE_USER"]
SNOWFLAKE_ACCOUNT = os.environ["SNOWFLAKE_ACCOUNT"]
# Path to your RSA private key (.p8) for key-pair authentication
SNOWFLAKE_PRIVATE_KEY_PATH = os.path.expanduser(os.environ["SNOWFLAKE_PRIVATE_KEY_PATH"])
# Only needed if you encrypted the private key with a passphrase
SNOWFLAKE_PRIVATE_KEY_PASSPHRASE = os.environ.get("SNOWFLAKE_PRIVATE_KEY_PASSPHRASE") or None


conn = snowflake.connector.connect(
    user=SNOWFLAKE_USER,
    account=SNOWFLAKE_ACCOUNT,  # e.g. "xy12345.us-east-1"
    authenticator="SNOWFLAKE_JWT",
    private_key_file=SNOWFLAKE_PRIVATE_KEY_PATH,
    private_key_file_pwd=SNOWFLAKE_PRIVATE_KEY_PASSPHRASE,
    warehouse='GDSONSNOWFLAKE',
    database='MTA',
    schema='PUBLIC',
)

In [10]:
cur = conn.cursor()
cur.execute("SELECT * FROM LINES")
lines = cur.fetch_pandas_all()
cur.close()
lines

      STARTING_STATION  NEXT_STATION RELATIONSHIPTYPE
0                    0             1          GOES_TO
1                    1             2          GOES_TO
2                    2             3          GOES_TO
3                    3             4          GOES_TO
4                    4             5          GOES_TO
...                ...           ...              ...
1393               336           408          GOES_TO
1394                32           336          GOES_TO
1395                34            32          GOES_TO
1396                61            34          GOES_TO
1397               417            61          GOES_TO

[1398 rows x 3 columns]

In [11]:
cur = conn.cursor()
cur.execute("SELECT * FROM stations")
stations = cur.fetch_pandas_all()
cur.close()
stations

                           STATION_NAME   ID
0           Van Cortlandt Park-242 - Bx    0
1                           238 St - Bx    1
2                           231 St - Bx    2
3                Marble Hill-225 St - M    3
4                            215 St - M    4
..                                  ...  ...
416              World Trade Center - M  416
417                        Broad St - M  417
418         Canarsie-Rockaway Pkwy - Bk  418
419  Middle Village-Metropolitan Av - Q  419
420                Bay Ridge-95 St - Bk  420

[421 rows x 2 columns]

# Creating a Projection
You can create a projection directly from python dataframes. We have two dataframes-- one that represents stations and one that represents lines.

Currently, Graph Analytics only accepts directed graphs. So we need to explicitly create the relationships going in the other direction.

In [12]:
lines = lines.rename(
    columns={
        'STARTING_STATION' : 'targetNodeId',
        'NEXT_STATION' : 'sourceNodeId'
    }
)

lines = lines[['targetNodeId', 'sourceNodeId']]
lines

      targetNodeId  sourceNodeId
0                0             1
1                1             2
2                2             3
3                3             4
4                4             5
...            ...           ...
1393           336           408
1394            32           336
1395            34            32
1396            61            34
1397           417            61

[1398 rows x 2 columns]

We do need to do some mild clean up to make sure that everything has the right names.

For the dataframe representing nodes:
- The first column should be called `nodeId`
- There can be no characters so we will have to drop the station names

For the dataframe representing relationships:
- We need to have columns called `sourceNodeId` and `targetNodeId`
- As well as what we want to call that relationship in a column called `relationshipType`

In [13]:
stations = stations.rename(columns={'ID': 'nodeId'})
nodes = stations[['nodeId']]
nodes

     nodeId
0         0
1         1
2         2
3         3
4         4
..      ...
416     416
417     417
418     418
419     419
420     420

[421 rows x 1 columns]

## Graph Construct
Using `graph.construct`, we can easily create a projection.

In [14]:
graph_name = "subways"

gds.graph.drop(graph_name, fail_if_missing=False)

G = gds.graph.construct("subways", nodes, lines)

Constructing graph: 100%|██████████| 100.0/100 [00:01<00:00, 82.78%/s, status: FINISHED]
GraphImportProcess: 100%|██████████| 100.0/100 [00:00<?, ?%/s, status: FINISHED]

## Returning Results
We will use Dijkstra shortest path to see how we can move through the system efficiently.

We can create a simple wrapper function below, so that we can use the names of stations rather than their `nodeIds`.

And with that, let's see how to get from Grand Army Plaza in Brooklyn to Times Square:

In [15]:
station_crosswalk = dict(zip(stations['STATION_NAME'], stations['nodeId']))

# Function to get the node IDs from station names and run Dijkstra
def get_shortest_path(source_station, target_station, G):
    # Map the station names to node IDs
    source_node_id = station_crosswalk.get(source_station)
    target_node_id = station_crosswalk.get(target_station)

    result = gds.shortest_path.dijkstra.stream(
          G,
          source_node=source_node_id,
          target_nodes=target_node_id
      )
    node_ids = result['nodeIds'][0]
    id_to_station = {v: k for k, v in station_crosswalk.items()}
    ordered_subset = {id_to_station[i]: i for i in node_ids if i in id_to_station}
    return ordered_subset

# Example usage
# Assuming 'G' is your graph
source_station = "Grand Army Plaza - Bk"
target_station = "Times Sq-42 St - M"

# Call the function
path_df = get_shortest_path(source_station, target_station, G)

path_df

Dijkstra: 100%|██████████| 100.0/100 [00:00<00:00, 804.19%/s, status: FINISHED]

{'Grand Army Plaza - Bk': 69,
 'Bergen St - Bk': 68,
 'Atlantic Av-Barclays Ctr - Bk': 67,
 'Canal St - M': 32,
 '14 St-Union Sq - M': 104,
 '34 St-Herald Sq - M': 230,
 'Times Sq-42 St - M': 24}

But what if one of those stations closed? What would be the quickest path there? Let's see what would happen if Herald Square was closed:

In [16]:
def exclude_node(nodes_df, lines_df, node_to_exclude):
    closed = nodes_df[nodes_df['nodeId'] != node_to_exclude]
    closed_lines = lines_df[
        (lines_df['sourceNodeId'] != node_to_exclude) &
        (lines_df['targetNodeId'] != node_to_exclude)
    ]
    return closed, closed_lines

closed_nodes, closed_lines = exclude_node(nodes, lines, 230)

We then need to create a new projection without Herald Square

In [17]:
graph_name = "exclude"

gds.graph.drop(graph_name, fail_if_missing=False)

G = gds.graph.construct(graph_name, closed_nodes, closed_lines)

Constructing graph: 100%|██████████| 100.0/100 [00:00<00:00, 103.89%/s, status: FINISHED]

And rerun to see the new path:

In [18]:
# Example usage
# Assuming 'G' is your graph
source_station = "Grand Army Plaza - Bk"
target_station = "Times Sq-42 St - M"

# Call the function
path_df = get_shortest_path(source_station, target_station, G)
print(path_df)

{'Grand Army Plaza - Bk': 69, 'Bergen St - Bk': 68, 'Atlantic Av-Barclays Ctr - Bk': 67, 'Canal St - M': 32, '14 St-Union Sq - M': 104, 'Grand Central-42 St - M': 103, '5 Av - M': 186, 'Times Sq-42 St - M': 24}

Don't forget to close your session!

In [19]:
sessions.delete(session_name="my-new-session-sm")

True